### ISSUE TITLE
Link to Github

### ISSUE THREAD

**Issue by szabgab** [patjoly/geo-gpx#1]
Most CPAN packages include a link to the git repository of their source code. It makes it easier to find it. It would be nice if you could also add this information to Geo::Gpx

Here is a blog post I wrote on how to do it: https://perlmaven.com/how-to-add-link-to-version-control-system-of-a-cpan-distributions

**Comment by patjoly** [comment]
Thank you Gabor for your feedback and providing your blog link and the plugin required to link the repo. Much appreciated.

Done, in the latest release uploaded to CPAN and here.
